name: CI - ML App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint code (basic style check)
        run: |
           pip install flake8
           flake8 . --ignore=E501 --max-line-length=120 || true
      
      - name: Run tests
        run: |
          pytest tests/ || echo "⚠️ No tests found, skipping..."
