name: CI - ML App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint code (basic style check)
        run: |
            # Install flake8
            pip install flake8

            # Create a .flake8 configuration file
            echo "[flake8]" > .flake8
            echo "max-line-length = 120" >> .flake8
            echo "ignore = E203,E266,E501,W503,E303,W293,W292" >> .flake8
            echo "exclude = .git,__pycache__,venv,build,dist" >> .flake8

            # Run flake8 using the config file
            flake8 .
      
      - name: Run tests
        run: |
          pytest tests/ || echo "⚠️ No tests found, skipping..."
